"""Export the public Chakravyuh dataset (tactic level, no message text).

    python -m chakravyuh.sim.export_public --sessions data/sessions.jsonl --out ../dataset

Responsible release: the public files keep the structure of each scam session (event types,
kill-chain stages, tactics, timing, payment features, mule hops) but drop the message text,
payee identifiers and the attacker genome, so they teach detection without handing anyone a
ready-made script. Full text is available to vetted researchers on request.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from collections import Counter
from pathlib import Path

KEEP_ATTRS = ["known_sender", "known", "minutes", "amount_ratio", "first_time", "payee_age_days", "cancelled",
              "kind", "disguise"]
SPLITS = {"train_pool": "train", "evolved": "train", "test_seen": "test_new_wording",
          "holdout_family": "test_unseen_family"}


def anonymise(session: dict) -> dict:
    return {
        "session_id": hashlib.sha256(session["session_id"].encode()).hexdigest()[:16],
        "split": "test_evolved" if session.get("split_hint") == "evolved" and session.get("variant_pool") == "test"
        else SPLITS.get(session.get("split_hint", ""), "train"),
        "label": session["label"],
        "family": session["family"],
        "language": session["language"],
        "channel": session["channel"],
        "generation": session.get("generation", 0),
        "outcome": "paid" if session["paid"] else "not_paid",
        "duration_hours": session.get("duration_hours"),
        "victim": {k: session["victim"][k] for k in ("age_band",)},
        "events": [{
            "t": e["t"], "type": e["type"], "stage": e["stage"], "tactics": e["tactics"],
            "has_text": bool(e.get("text")),
            "attrs": {k: v for k, v in e.get("attrs", {}).items() if k in KEEP_ATTRS},
        } for e in session["events"]],
    }


def card(stats: dict) -> str:
    rows = "\n".join(f"| {k} | {v['sessions']:,} | {v['scam']:,} | {v['legit']:,} |" for k, v in stats["splits"].items())
    fams = ", ".join(f"{k} ({v})" for k, v in stats["families"].most_common())
    return f"""# Chakravyuh scam-session dataset

Synthetic scam and legitimate payment *sessions*: the messages, calls, app events and payments
from first contact until money leaves the account, labelled at every step with the kill-chain
stage and persuasion tactics. Generated by the Chakravyuh multi-agent simulator, including
scam variants evolved to evade a detector.

## Files

- `sessions.jsonl.gz`: one session per line, gzip-compressed (schema below)
- `README.md`: this card

## Splits

| Split | Sessions | Scam | Legitimate |
| --- | --- | --- | --- |
{rows}

`test_new_wording` uses message wordings never seen in `train`; `test_unseen_family` is a scam
family never seen in training; `test_evolved` holds the last simulator generations.

## Families

{fams}

## Schema

```json
{{"session_id": "...", "split": "train", "label": 1, "family": "investment_group", "language": "hinglish",
 "channel": "whatsapp", "generation": 0, "outcome": "paid", "duration_hours": 96.4,
 "victim": {{"age_band": "60+"}},
 "events": [{{"t": 0.0, "type": "MSG_RECV", "stage": "contact", "tactics": ["greed", "social_proof"],
             "has_text": true, "attrs": {{"known_sender": false}}}}]}}
```

Event types: MSG_RECV, MSG_SENT, CALL, SCREEN_SHARE, REMOTE_APP, LINK_OPEN, APK_INSTALL, UPI_OPEN,
PAYEE_NEW, FD_BREAK, PAY, RECV. Stages: contact, hook, trust, pressure, payment_ask, payment, cashout.
`attrs.disguise` marks a genuine-looking opener an evolved attacker borrowed: it is not scam evidence.

## What is left out, and why

Message text, payee identifiers and the attacker genomes are removed so the release teaches
detection without providing ready-made scam scripts. Researchers who need text can request it.

## Limitations

All sessions are simulated from templates (optionally LLM-paraphrased). They capture the
structure of known Indian scam workflows but not the full variety of real conversations, so
models must be validated on real data before deployment.

## Licence

CC BY 4.0. Cite as: Saraswat, T. Chakravyuh scam-session dataset ({stats['version']}).
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sessions", default="data/sessions.jsonl")
    ap.add_argument("--out", default="../dataset")
    ap.add_argument("--version", default="v0.1")
    args = ap.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    splits: dict[str, dict] = {}
    families: Counter = Counter()
    with open(args.sessions, encoding="utf-8") as f, gzip.open(out / "sessions.jsonl.gz", "wt", encoding="utf-8") as g:
        for line in f:
            s = anonymise(json.loads(line))
            g.write(json.dumps(s, ensure_ascii=False) + "\n")
            st = splits.setdefault(s["split"], {"sessions": 0, "scam": 0, "legit": 0})
            st["sessions"] += 1
            st["scam" if s["label"] else "legit"] += 1
            families[s["family"]] += 1
    (out / "README.md").write_text(card({"splits": splits, "families": families, "version": args.version}))
    print(f"wrote {sum(v['sessions'] for v in splits.values())} sessions to {out}/")


if __name__ == "__main__":
    main()
